### ISSUE TITLE
Missing Bundle Resources on Pod

### ISSUE THREAD

**Issue by lucferbux** [VictorZhang2014/ZRQRCodeViewController#2]
The method 
`- (instancetype)initWithBundleName:(NSString *)bundleName`
 returns nil path when searching the bundle, works with 
`NSURL *bundleURL = [[NSBundle bundleForClass:[self class]] URLForResource:@"ZRQRCode" withExtension:@"bundle"]; `
instead, this way you could find the images.

**Comment by VictorZhang2014** [comment]
If the method returned nil, then selecting project -> Build Phases -> Copy Bundle Resources might not add `ZRQRCode.bundle`. 

If there is the `ZRQRCode.bundle` in the Copy Bundle Resources item, the `nil` is still existing. your solution works. 

And in my project, `[[NSBundle mainBundle] pathForResource:bundleName ofType:@"bundle"];`  works.

Both are correct.

**Comment by lucferbux** [comment]
Hi! Thanks for the quick response!
`ZRQRCode.bundle` is added in Copy Bundle Resources, problem is that I'm calling the mainBundle through a CocoaPod Framework won't work, as it is described in this post [http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/](url) 

So unfortunately, `[[NSBundle mainBundle] pathForResource:bundleName ofType:@"bundle"];` won't work in a Cocoa project to load the bundle, you must call your bundle class in order to get it.

Even though, your Pod is incredibly great, good UI and very careful design, thanks for sharing it.

Regards,
Lucas.

**Comment by VictorZhang2014** [comment]
Thank you for the solution.
I got it. I'll take it into the project.

Sincerely,
Victor.
