### ISSUE TITLE
我在一个nav的按钮点击事件中添加了扫描二维码的代码遇到了BUG

### ISSUE THREAD

**Issue by JackCrazyDay** [VictorZhang2014/ZRQRCodeViewController#3]
DJ_XjjlViewController.m:134:13: No visible @interface for 'ZRQRCodeViewController' declares the selector 'QRCodeScanningWithViewController:completion:'
这个方法不能使用

补充：我在删除了你的   README文件里面的那句代码[qrCode QRCodeScanningWithViewController:self completion:^(NSString *strValue) {
    NSLog(@"strValue = %@ ", strValue);
    if([[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:strValue]]){
        [[UIApplication sharedApplication] openURL:[NSURL URLWithString:strValue]];
    } else {
        UIAlertView *alertView = [[UIAlertView alloc] initWithTitle:@"Ooooops!" message:[NSString stringWithFormat:@"The result is %@", strValue] delegate:nil cancelButtonTitle:@"Cancel" otherButtonTitles:nil, nil];
        [alertView show];
    }
}];

自己重写   发现这个方法已经改变了
[qrCode QRCodeScanningWithViewController:self completion:^(NSString *strValue) {
        
    } failure:^(NSString *message) {
        
    }];

**Comment by VictorZhang2014** [comment]
谢谢提醒~   我更新了库之后，忘记更新README了，现在已经更新了
